apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-hello
  labels:
    app: docker-k8s-springboot
spec:
  selector:
    matchLabels:
      app: docker-k8s-springboot
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docker-k8s-springboot
    spec:
      containers:
      - image: kvenbakk/hello-docker
        name: docker-k8s-springboot
        ports:
        - containerPort: 8080
